// The support report: what is collected (and what must NEVER be in it), how it reaches the IT department's network folder, what the user sees when the network is NOT there
// (a quiet message + "Save as file"), the box, the automatic question after a crash / hang, and the reader that explains a report.
// The "IT folder" is a temporary local folder here; an unreachable UNC address (a reserved, non-routable IP) stands for a PC that is away from the company network.
// Run: env -u ELECTRON_RUN_AS_NODE ./node_modules/electron/dist/electron.exe scripts/verify-report.js
const { app, dialog } = require("electron");
const path = require("path"), fs = require("fs"), os = require("os");
app.commandLine.appendSwitch("disable-features", "CalculateNativeWinOcclusion");
setTimeout(() => { console.log("WATCHDOG"); app.exit(2); }, 330000).unref();
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "pbcalc-report-"));
const shareDir = path.join(tmp, "it-share", "pbcalc-report");
const OFFLINE = "\\\\192.0.2.1\\it\\Ravi\\browser\\pbcalc-report";   // 192.0.2.1 = reserved for documentation: nothing answers there
require("../electron/constants").dataDir = () => path.join(tmp, "UserData");
fs.mkdirSync(path.join(tmp, "UserData"), { recursive: true });
fs.mkdirSync(shareDir, { recursive: true });
fs.writeFileSync(path.join(tmp, "UserData", "settings.json"), JSON.stringify({ showBookmarksBar: false, reportShare: shareDir }));
fs.writeFileSync(path.join(tmp, "UserData", "diag-session.json"), JSON.stringify({ startedAt: "2026-10-09T08:00:00.000Z", lastAt: "2026-10-09T08:40:00.000Z", upSec: 2400, version: "0.1.5", quitRequested: false, tabs: 6, recent: [{ at: "2026-10-09T08:39:55.000Z", freeMB: 310, sysCpu: 96, lagMs: 4200, procs: {}, pages: [{ p: 3, mb: 1500, cpu: 20 }] }], events: [], pageLoads: [], exceptions: [{ at: "x", origin: "uncaughtException", message: "boom", stack: "" }] }));   // what a PBCalc that was KILLED leaves behind
let nextSave = { canceled: true };
dialog.showSaveDialog = async () => nextSave;   // the native "save as" window cannot be driven; it answers what the test says
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const results = [];
const check = (name, cond, extra) => { results.push({ name, pass: !!cond }); console.log("  .. " + (cond ? "ok " : "FAIL ") + name + (!cond && extra !== undefined ? "  <" + String(extra).slice(0, 300) + ">" : "")); };
const errors = [];
process.on("uncaughtException", (e) => errors.push(e && e.message));
const walk = (dir) => { const out = []; try { for (const e of fs.readdirSync(dir, { withFileTypes: true })) { const p = path.join(dir, e.name); if (e.isDirectory()) out.push(...walk(p)); else out.push(p); } } catch (_) {} return out; };
const saved = () => walk(shareDir).filter((f) => f.endsWith(".json"));
let rdRef = null;
const waitDialog = async () => { for (let i = 0; i < 50; i++) { const x = rdRef._win(); if (x && !x.isDestroyed()) { try { if (await x.webContents.executeJavaScript('!!document.getElementById("rd-computer") && document.getElementById("rd-computer").textContent.length > 0')) return x; } catch (_) {} } await sleep(150); } return null; };
let lastMsg = "";
const waitMsg = async (re) => { for (let i = 0; i < 100; i++) { try { const x = rdRef._win(); if (!x || x.isDestroyed()) return; const t = await x.webContents.executeJavaScript('document.getElementById("rd-msg").textContent', true); if (re.test(t)) { lastMsg = t; return; } } catch {} await sleep(250); } };
const waitClosed = async () => { for (let i = 0; i < 50; i++) { if (!rdRef._win()) return true; await sleep(150); } return false; };

(async () => {
  try {
    require("../electron/main.js");
    await app.whenReady(); await sleep(3500);
    const state = require("../electron/state");
    const tm = require("../electron/tabs/tabManager");
    const dg = require("../electron/diagnostics");
    const http = require("http");
    const web = http.createServer((q, s) => { setTimeout(() => { s.setHeader("content-type", "text/html"); s.end("<html><title>t</title><body>hi</body></html>"); }, 250); }).listen(0, "127.0.0.1");
    await new Promise((r) => web.once("listening", r));
    tm.createTab("http://127.0.0.1:" + web.address().port + "/"); await sleep(1500);
    process.emit("uncaughtExceptionMonitor", new Error("boom while loading https://secret.example/a?b=1 ok"), "uncaughtException");
    const rd = require("../electron/reportDialog"); rdRef = rd;
    const settings = require("../electron/settings");
    const user = os.userInfo().username;

    console.log("-- what is collected");
    await sleep(11000);   // the recorder samples every 5 s
    const rep = await dg.collect({ note: "N".repeat(3000), trigger: "manual" });
    const json = JSON.stringify(rep);
    check("the report has every part (format 2)", rep.format === 2 && ["reportId", "trigger", "createdAt", "local", "computer", "app", "windows", "hardware", "gpuFeatures", "memory", "load", "otherPrograms", "network", "storage", "windowsFacts", "appState", "startupMs", "processesNow", "recent", "pageLoads", "events", "exceptions", "previousSession", "note"].every((k) => k in rep), Object.keys(rep).join());
    console.log("-- the added facts (what makes a crash / a slow PC explainable)");
    check("the whole computer's CPU is recorded in every sample after the first (to tell 'PBCalc is busy' from 'something else is')", rep.recent.slice(1).every((s) => typeof s.sysCpu === "number") && rep.recent.length >= 2, JSON.stringify(rep.recent.map((s) => s.sysCpu)));
    check("each sample says how big each TAB's page is, by position (never by address): memory growth of one tab shows", rep.recent.some((s) => Array.isArray(s.pages) && s.pages.some((p) => p.p >= 1 && p.mb > 0)) && typeof rep.recent[0].mainMB === "number", JSON.stringify(rep.recent[rep.recent.length - 1].pages));
    check("the processes are named by role (shell / page1 / helper:...), not by site", rep.processesNow.some((p) => p.role === "shell") && rep.processesNow.some((p) => /^page\d+$/.test(p.role)) && rep.processesNow.some((p) => /^helper:/.test(p.role)), JSON.stringify(rep.processesNow.map((p) => p.role)));
    check("Windows memory, commit and page file are in it (or Windows facts are marked unavailable)", rep.windowsFacts.unavailable === true || (rep.memory.windows && rep.memory.windows.commitLimitMB > 0 && Array.isArray(rep.memory.pageFile)), JSON.stringify(rep.memory));
    check("how busy the whole computer / the disk is right now is in it", rep.windowsFacts.unavailable === true || (rep.load && typeof rep.load.cpuPct === "number" && typeof rep.load.diskPct === "number"), JSON.stringify(rep.load));
    check("which programs use the CPU is in it (names only)", rep.windowsFacts.unavailable === true || (Array.isArray(rep.otherPrograms.topCpu) && rep.otherPrograms.topCpu.every((p) => typeof p.name === "string")), JSON.stringify(rep.otherPrograms.topCpu).slice(0, 200));
    check("the APPS open (Task Manager > Apps only: no Background / Windows processes) are in it with the memory of all their processes; Windows' total / free RAM too", rep.windowsFacts.unavailable === true || (rep.otherPrograms.openApps.length >= 1 && rep.otherPrograms.openApps.every((p) => p.name && p.windows >= 0 && p.processes >= 1 && p.workingSetMB >= 0) && !rep.otherPrograms.openApps.some((p) => /^(svchost|ApplicationFrameHost|TextInputHost)$/i.test(p.name)) && !("topMemory" in rep.otherPrograms) && !("processCount" in rep.otherPrograms) && rep.memory.windows.physTotalMB > 0 && rep.hardware.ramTotalMB > 0), JSON.stringify(rep.otherPrograms.openApps).slice(0, 300));
    check("a failed Windows-facts part says WHY (errors) instead of going silent, and memory still comes from Node", await (async () => { const wf = require("../electron/winFacts"); const r2 = await wf.windowsFacts({ timeoutMs: 1 }); return !!r2.errors && Object.values(r2.errors).every((e) => /timeout|exit|could not|JSON/.test(e)) && r2.memory.physTotalMB > 0; })());
    check("'available' memory + whether Windows is swapping + Defender state are in it (free RAM alone ignores the cache Windows hands back)", rep.windowsFacts.unavailable === true || (rep.memory.available && rep.memory.available.availableMB > 0 && "pagesInPerSec" in rep.memory.available && (rep.windowsFacts.defender === null || typeof rep.windowsFacts.defender.realTime === "boolean")), JSON.stringify(rep.memory.available) + JSON.stringify(rep.windowsFacts.defender));
    check("start-up steps are recorded between launch and the first picture (so a 46 s start says WHICH step)", ["appReady", "windowCreated", "shellStartLoading", "shellDomReady", "shellFinishLoad"].every((k) => typeof rep.startupMs[k] === "number"), JSON.stringify(rep.startupMs));
    check("network speed is in it (the IT computer, the internet, a name lookup)", rep.network && ["itComputerMs", "internetMs", "dnsMs"].every((k) => k in rep.network), JSON.stringify(rep.network));
    check("Windows crash / hang entries carry the faulting module and exception code (the part that says WHY)", rep.windowsFacts.unavailable === true || rep.windowsFacts.pbcalcEvents.every((e) => "module" in e && "code" in e && "app" in e), JSON.stringify(rep.windowsFacts.pbcalcEvents).slice(0, 300));
    check("how long a page took to load is recorded - a number and the time, never the address", rep.pageLoads.length >= 1 && rep.pageLoads.every((p) => typeof p.ms === "number" && !("url" in p)), JSON.stringify(rep.pageLoads));
    check("the SITE's host name is in the report (owner's decision): page loads, open tabs and the tab samples - host only, no path / query", rep.pageLoads.some((x) => x.host === "127.0.0.1") && rep.openTabs.some((t) => t.host === "127.0.0.1" && t.p >= 1) && rep.recent.some((sm) => (sm.pages || []).some((q) => q.host === "127.0.0.1")) && !/127\.0\.0\.1[:\/]/.test(JSON.stringify(rep)), JSON.stringify(rep.openTabs));
    check("an error inside the main program is recorded and any web address in it is removed", rep.exceptions.length >= 1 && /boom while loading <url> ok/.test(rep.exceptions[0].message), JSON.stringify(rep.exceptions));
    check("the remote-session type is in it (Console / RDP...)", typeof rep.windows.sessionType === "string" && rep.windows.edition !== undefined);
    check("a PBCalc that was KILLED last time leaves its last minutes: the report carries them as previousSession", !!rep.previousSession && rep.previousSession.endedUncleanly === true && rep.previousSession.ranSec === 2400 && rep.previousSession.recent[0].freeMB === 310 && rep.previousSession.recent[0].pages[0].mb === 1500, JSON.stringify(rep.previousSession && rep.previousSession.recent));
    check("a normal end removes the session copy (cleanExit)", await (async () => { dg.persistSession(); const f = path.join(tmp, "UserData", "diag-session.json"); const had = fs.existsSync(f); dg.cleanExit(); return had && !fs.existsSync(f); })());
    check("the session copy is on the keep list (the wipe at start must not delete it) and holds numbers only", require("../electron/privacy").KEEP.has("diag-session.json") && require("../electron/privacy").KEEP.has("diag-previous.json"));
    check("scrub() removes addresses from any text", dg.scrub("failed to load https://a.b/c?d=1 and ftp://x/y end") === "failed to load <url> and <url> end");
    check("the computer is named and has a stable random install id (not the Windows login)", rep.computer.name === os.hostname() && /^[0-9a-f-]{36}$/.test(rep.computer.installId) && (await dg.collect()).computer.installId === rep.computer.installId && settings.get("installId") === rep.computer.installId);
    check("date and time are in it (ISO, local text, zone)", /^\d{4}-\d\d-\d\dT/.test(rep.createdAt) && rep.local.length > 8 && Number.isInteger(rep.timezoneOffsetMin));
    check("hardware facts are real (RAM, CPU threads, a graphics card, displays)", rep.hardware.ramTotalMB > 1000 && rep.hardware.cpuThreads >= 1 && rep.hardware.gpu.length >= 1 && rep.hardware.displays.length >= 1 && rep.windows.version.length > 3);
    check("the recorder has samples of the last minutes (memory + CPU per process type, free RAM, timer lateness, tabs)", rep.recent.length >= 1 && rep.recent[0].procs && Object.keys(rep.recent[0].procs).length >= 3 && rep.recent[0].freeMB > 0 && "lagMs" in rep.recent[0] && "tabs" in rep.recent[0], JSON.stringify(rep.recent[0]));
    check("the start-up timeline has marks", rep.startupMs.appReady > 0 && rep.startupMs.windowReadyToShow > 0 && rep.startupMs.windowVisible >= rep.startupMs.windowReadyToShow, JSON.stringify(rep.startupMs));
    check("Windows facts came back (antivirus / disks / power plan), or are marked unavailable", rep.windowsFacts.unavailable === true || (rep.windowsFacts.antivirus !== null && rep.windowsFacts.disks !== null), JSON.stringify(rep.windowsFacts));
    check("the note is cut at 2000 characters", rep.note.length === 2000);
    check("the report is small (" + Math.round(json.length / 1024) + " KB)", json.length < 300 * 1024);
    check("NO web address anywhere in it (no '://')", !/:\/\//.test(json.replace(/"note":"[^"]*"/, "")), (json.match(/.{30}:\/\/.{30}/) || [])[0]);
    check("the Windows login name is nowhere in it", !user || !new RegExp(user.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i").test(json.replace(/"computer":\{"name":"[^"]*"/, "")) || user.toLowerCase() === os.hostname().toLowerCase(), user);
    check("nothing about pages: no title / url / cookie / password / bookmark keys", !/"(url|title|cookie|cookies|password|bookmarks?|history|favicon)"\s*:/i.test(json));
    check("redact() hides the login in a path and leaves other text alone", dg.redact({ p: "C:\\Users\\" + user + "\\AppData\\Local\\PBCalc", q: "Users stay", r: ["/Users/" + user + "/x"] }).p === "C:\\Users\\<user>\\AppData\\Local\\PBCalc" && dg.redact({ q: "Users stay" }).q === "Users stay" && dg.redact({ r: ["/Users/" + user + "/x"] }).r[0] === "/Users/<user>/x");
    check("the recorder keeps its data in memory only (no file with samples in the data folder)", !walk(path.join(tmp, "UserData")).some((f) => /report|sample|recent|diagnos/i.test(path.basename(f))));

    console.log("-- into the IT department's folder");
    check("the default folder is the IT department's: \\\\192.168.0.3\\it\\Ravi\\browser\\pbcalc-report", dg.DEFAULT_SHARE === "\\\\192.168.0.3\\it\\Ravi\\browser\\pbcalc-report", dg.DEFAULT_SHARE);
    check("settings.json (reportShare) can point it elsewhere", dg.reportShare() === shareDir);
    const r1 = await dg.send(rep);
    const f1 = saved();
    check("send() puts the report in <folder>\\<yyyy-mm-dd>\\<computer>_<id8>_<hhmmss>_<trigger>_<reportId8>.json", r1.ok === true && f1.length === 1 && /\d{4}-\d\d-\d\d$/.test(path.basename(path.dirname(f1[0]))) && new RegExp("^" + os.hostname().replace(/[^A-Za-z0-9._-]/g, "_") + "_[0-9a-f-]{8}_\\d{6}_manual_[0-9a-f-]{8}\\.json$").test(path.basename(f1[0])), JSON.stringify(r1) + " " + f1.join());
    const back = JSON.parse(fs.readFileSync(f1[0], "utf8"));
    check("what is in the file is what was collected (same id, note, computer)", back.reportId === rep.reportId && back.note === rep.note && back.computer.installId === rep.computer.installId);
    check("no half-written .part file is left", !walk(shareDir).some((f) => f.endsWith(".part")));
    check("once the report that carried the previous session is delivered, it is not carried again", !fs.existsSync(path.join(tmp, "UserData", "diag-previous.json")) && dg.previousSession() === null);
    const r1b = await dg.send({ ...rep, reportId: "second-id-1234" });
    check("two reports of the same second do not overwrite each other", r1b.ok === true && saved().length === 2);
    const bigRep = { ...rep, recent: Array.from({ length: 12000 }, () => rep.recent[0] || { at: "x", procs: {} }) };
    check("a report over 2 MB is trimmed (oldest recorder samples first) before it is written", Buffer.byteLength(JSON.stringify(bigRep)) > dg.MAX_REPORT_BYTES && Buffer.byteLength(JSON.stringify(dg.fitSize(bigRep))) <= dg.MAX_REPORT_BYTES && dg.fitSize(bigRep).note === bigRep.note, Buffer.byteLength(JSON.stringify(dg.fitSize(bigRep))));
    const t0 = Date.now();
    const rOff = await dg.send(rep, { dir: OFFLINE });
    const offMs = Date.now() - t0;
    check("away from the company network (the share's computer does not answer): { offline: true } in a few seconds, no exception", rOff.ok === false && rOff.offline === true && offMs < 7000, JSON.stringify(rOff) + " " + offMs + " ms");
    fs.writeFileSync(path.join(tmp, "afile.txt"), "x");
    const rBad = await dg.send(rep, { dir: path.join(tmp, "afile.txt", "sub") });
    check("a folder that answers but cannot take the file is NOT 'offline' (it says why, no exception)", rBad.ok === false && rBad.offline === false && !!rBad.reason, JSON.stringify(rBad));
    const rOk = await dg.saveToFile(rep, path.join(tmp, "copy.json"));
    console.log("-- a PC on the company network that is not signed in to the file server");
    const lockDir = path.join(tmp, "locked-share"); fs.mkdirSync(lockDir, { recursive: true });
    const dayName = dg.reportFileName(rep).day;
    fs.writeFileSync(path.join(lockDir, dayName), "x");        // a FILE where the day folder must go: the first write is refused, like a share that wants a sign-in
    const calls = [];
    const fakeLogin = async () => { calls.push("login"); try { fs.unlinkSync(path.join(lockDir, dayName)); } catch (_) {} return { connected: true, disconnect: async () => { calls.push("disconnect"); } }; };
    const rLog = await dg.send(rep, { dir: lockDir, login: fakeLogin });
    check("a refused write -> ONE sign-in, the write again, then OUR connection is removed (login, then disconnect, once each, in that order)", rLog.ok === true && calls.join(",") === "login,disconnect" && fs.existsSync(rLog.file), JSON.stringify(rLog) + calls.join());
    calls.length = 0;
    fs.rmSync(path.join(lockDir, dayName), { recursive: true, force: true }); fs.writeFileSync(path.join(lockDir, dayName), "x");
    const rNoLogin = await dg.send(rep, { dir: lockDir, login: async () => { calls.push("login"); return { connected: false, disconnect: async () => { calls.push("disconnect"); } }; } });
    check("when the sign-in fails (or a connection of the user's own exists) -> not sent, no exception, nothing to remove", rNoLogin.ok === false && calls.join(",") === "login", JSON.stringify(rNoLogin) + calls.join());
    calls.length = 0;
    const rThrow = await dg.send(rep, { dir: lockDir, login: async () => { throw new Error("boom"); } });
    check("a sign-in that throws is contained", rThrow.ok === false);
    const rOffNoLogin = await dg.send(rep, { dir: OFFLINE, login: async () => { calls.push("login"); return { connected: false, disconnect: async () => {} }; } });
    check("a PC away from the network never tries to sign in", rOffNoLogin.offline === true && !calls.includes("login"));
    calls.length = 0;
    const ok1 = await dg.send(rep, { dir: shareDir, login: async () => { calls.push("login"); return { connected: false, disconnect: async () => {} }; } });
    check("a normal write (already signed in) never signs in", ok1.ok === true && calls.length === 0);
    const sl = require("../electron/shareLogin");
    const t1 = Date.now();
    const rReal = await sl.login("\\\\127.0.0.1\\pbc-no-such-share\\x");
    check("the real PowerShell helper runs: a share that does not exist -> not connected, no exception, nothing left over", rReal.connected === false && Date.now() - t1 < 15000, JSON.stringify(rReal));
    check("shareRoot() keeps server + share only", sl.shareRoot("\\\\192.168.0.3\\it\\Ravi\\browser\\pbcalc-report") === "\\\\192.168.0.3\\it" && sl.shareRoot("C:\\x") === null);
    const dataText = (function walkAll(d) { let t = ""; for (const f of fs.readdirSync(d, { withFileTypes: true })) { const q = path.join(d, f.name); if (f.isDirectory()) t += walkAll(q); else { try { t += fs.readFileSync(q, "utf8"); } catch (_) {} } } return t; })(tmp);
    check("the password is in no report and in no file of the data folder", !dataText.includes("11511151") && !JSON.stringify(rep).includes("11511151"));
    check("no use of Credential Manager / persistent connections in the helper", !/cmdkey|savecred|persistent/i.test(fs.readFileSync(path.join(__dirname, "..", "electron", "shareLogin.js"), "utf8").replace(/\/\/.*$/gm, "")));
    check("saveToFile() writes the same report to a file of the user's choice", JSON.parse(fs.readFileSync(rOk, "utf8")).reportId === rep.reportId);

    console.log("-- the box the user sees (Settings > Support > Send report)");
    const settingsTab = (tm.openSettings(), await sleep(1500), tm.getActiveTab());
    check("Settings has the Support card with a 'Send report' button", (await settingsTab.view.webContents.executeJavaScript('!!document.getElementById("send-report") && /Support/.test(document.getElementById("support-card").textContent)')) === true);
    const n0 = saved().length;
    await settingsTab.view.webContents.executeJavaScript('document.getElementById("send-report").click(), 1');
    let w = await waitDialog();
    const dj = (code) => w.webContents.executeJavaScript(code, true);
    check("pressing it opens the box (nothing is sent yet)", !!w && saved().length === n0);
    check("the box says what is sent / never sent, shows the computer name, asks for a note and offers 'Save as file' from the start", (await dj('document.getElementById("rd-computer").textContent')) === os.hostname() && /never sent/i.test(await dj("document.body.textContent")) && (await dj('!!document.getElementById("rd-note") && !document.getElementById("rd-save").hidden')) === true);
    check("Cancel closes it and sends nothing", await (async () => { await dj('document.getElementById("rd-cancel").click(), 1'); return (await waitClosed()) && saved().length === n0; })());
    rd.ask({ trigger: "manual" }); w = await waitDialog();
    await dj('document.getElementById("rd-note").value = "Opening the ERP takes a minute"; 1');
    await dj('document.getElementById("rd-send").click(), 1'); await waitMsg(/sent to the (IT|Software)|could not|not connected|was saved/);
    const newest = saved().map((f) => JSON.parse(fs.readFileSync(f, "utf8"))).find((j) => j.note === "Opening the ERP takes a minute");
    check("Send puts the report in the IT folder WITH the note typed in the box", !!newest && newest.trigger === "manual" && saved().length === n0 + 1, saved().length + " n0=" + n0 + " msg=" + lastMsg);
    check("the box then says it was sent to the (IT|Software) department", /sent to the (IT|Software) department/.test(lastMsg));
    check("...and closes by itself", await waitClosed());

    console.log("-- a PC that is NOT on the company network");
    settings.set("reportShare", OFFLINE);
    rd.ask({ trigger: "manual" }); w = await waitDialog();
    await dj('document.getElementById("rd-note").value = "No network here"; 1');
    await dj('document.getElementById("rd-send").click(), 1');
    let msg = "";
    for (let i = 0; i < 40 && !/not connected/.test(msg); i++) { await sleep(300); msg = await dj('document.getElementById("rd-msg").textContent'); }
    check("it says in plain words: not connected to the company network - tell the IT department / save the file", /not connected to the company network/.test(msg) && /IT department/.test(msg) && /Save as file/.test(msg), msg);
    check("...in a calm (amber) style, not a red error, and no technical words", (await dj('document.getElementById("rd-status").className')) === "status warn" && !/ECONN|ETIMEDOUT|ENOTFOUND|EHOST|server answered|errno|socket|502|404|405/i.test(msg), msg);
    check("the buttons are usable again ('Try again', 'Save as file')", (await dj('document.getElementById("rd-send-label").textContent')) === "Try again" && (await dj('!document.getElementById("rd-send").disabled && !document.getElementById("rd-save").disabled')) === true);
    const filesBefore = fs.readdirSync(tmp).filter((f) => /^offline-/.test(f)).length;
    nextSave = { canceled: true };
    await dj('document.getElementById("rd-save").click(), 1'); await sleep(1500);
    check("Save as file, then Cancel in the file window: nothing is written, the box stays", fs.readdirSync(tmp).filter((f) => /^offline-/.test(f)).length === filesBefore && !!rd._win());
    nextSave = { canceled: false, filePath: path.join(tmp, "offline-1.json") };
    await dj('document.getElementById("rd-save").click(), 1'); await waitMsg(/was saved/);
    for (let i = 0; i < 30 && !fs.existsSync(path.join(tmp, "offline-1.json")); i++) await sleep(200);
    const fileBack = fs.existsSync(path.join(tmp, "offline-1.json")) ? JSON.parse(fs.readFileSync(path.join(tmp, "offline-1.json"), "utf8")) : null;
    check("Save as file writes the report (with the note) where the user chose", !!fileBack && fileBack.note === "No network here" && fileBack.computer.name === os.hostname() && fileBack.trigger === "manual");
    await sleep(500);
    check("the box then tells the user to give the file to the IT department", /was saved/.test(lastMsg) && /(IT|Software) department/.test(lastMsg));
    settings.set("reportShare", shareDir);
    await dj('document.getElementById("rd-send").click(), 1'); await waitMsg(/sent to the (IT|Software)|could not|not connected|was saved/);
    check("back in the office, Try again works", /sent to the (IT|Software) department/.test(lastMsg));
    w.close(); await waitClosed();
    settings.set("reportShare", path.join(tmp, "afile.txt", "sub"));
    rd.ask({ trigger: "manual" }); w = await waitDialog();
    await dj('document.getElementById("rd-send").click(), 1'); await waitMsg(/could not be put/);
    check("a folder that refuses the file gets its own plain sentence (also with 'Save as file')", /could not be put in the (IT|Software) department's folder/.test(await dj('document.getElementById("rd-msg").textContent')) && (await dj('document.getElementById("rd-status").className')) === "status warn");
    w.close(); await waitClosed();
    settings.set("reportShare", shareDir);

    console.log("-- the question PBCalc asks by itself after a problem");
    rd._resetGap();
    check("after a crash it asks (the box says so)", rd.promptAfterProblem("crash") === true && await (async () => { w = await waitDialog(); return !!w && /stopped working/.test(await dj('document.getElementById("rd-reason").textContent')) && (await dj('document.getElementById("rd-title").textContent')) === "PBCalc had a problem"; })());
    w.close(); await waitClosed();
    check("...but not again within 30 minutes (no nagging)", rd.promptAfterProblem("hang") === false && !rd._win());
    rd._resetGap(); state.calcMode = true;
    check("it never asks while the calculator screen is showing", rd.promptAfterProblem("crash") === false); state.calcMode = false;
    state.restricted = true;
    check("...nor in Restricted Mode", rd.promptAfterProblem("crash") === false); state.restricted = false;
    tm.createTab("data:text/html,<h1>victim</h1>"); await sleep(1500);
    const evBefore = dg._events().length;
    tm.getActiveTab().view.webContents.forcefullyCrashRenderer(); await sleep(2500);
    check("a real page crash is recorded (reason, no address) and the box opens", dg._events().slice(evBefore).some((e) => e.kind === "render-process-gone" && e.reason === "crashed" && !("url" in e)) && !!(await waitDialog()), JSON.stringify(dg._events().slice(evBefore)));
    if (rd._win()) { rd._win().close(); await waitClosed(); }
    rd._resetGap();
    const evN = dg._events().length;
    check("pages freed by the memory saver are NOT reported as crashes", await (async () => { await tm.discardIdleTabs({ afterMs: 0 }); await sleep(1500); return dg._events().length === evN && !rd._win(); })());

    console.log("-- the reader (diagnose-report.js)");
    const { analyse } = require("./diagnose-report.js");
    const a = analyse(rep);
    check("it reads a real report: facts + at least one finding, no exception", a.facts.length >= 6 && a.findings.length >= 1);
    const lvl = (r) => analyse(r).findings.map((f) => f.level + ":" + f.title);
    const mkr = (o) => JSON.parse(JSON.stringify({ ...rep, memory: { ...rep.memory, available: null }, ...o }));   // synthetic cases start without the live PC's "available memory" figure
    const lowRam = mkr({ hardware: { ...rep.hardware, ramTotalMB: 8192, ramFreeMB: 300 }, recent: [{ at: "x", freeMB: 300, lagMs: 0, tabs: 3, discarded: 0, procs: { Tab: { n: 2, cpu: 1, privMB: 200 } } }, { at: "y", freeMB: 250, lagMs: 0, tabs: 3, discarded: 0, procs: { Tab: { n: 2, cpu: 1, privMB: 200 } } }, { at: "z", freeMB: 280, lagMs: 0, tabs: 3, discarded: 0, procs: { Tab: { n: 2, cpu: 1, privMB: 200 } } }] });
    check("low free RAM -> 'short of memory' HIGH", lvl(lowRam).some((s) => /HIGH:The computer is short of memory/.test(s)), lvl(lowRam).join("|"));
    const soft = mkr({ gpuFeatures: { ...rep.gpuFeatures, gpu_compositing: "disabled_software", rasterization: "disabled_software" } });
    check("software drawing -> 'drawn by the processor' HIGH", lvl(soft).some((s) => /HIGH:Pages are drawn by the processor/.test(s)), lvl(soft).join("|"));
    const lag = mkr({ recent: [{ at: "x", freeMB: 4000, lagMs: 2500, tabs: 1, discarded: 0, procs: {} }] });
    check("a 2.5 s late timer -> 'main program froze' HIGH", lvl(lag).some((s) => /HIGH:PBCalc's main program froze/.test(s)), lvl(lag).join("|"));
    const crash = mkr({ events: [{ kind: "render-process-gone", reason: "oom", at: "t" }, { kind: "unresponsive", type: "browserView", at: "t" }] });
    check("a crash (out of memory) and a 'not responding' -> both HIGH", lvl(crash).some((s) => /crashed/.test(s)) && lvl(crash).some((s) => /not responding/.test(s)), lvl(crash).join("|"));
    const slow = mkr({ startupMs: { windowVisible: 15000 }, storage: { ...rep.storage, disks: ["HDD/SATA"], dataFolderFreeGB: 1 }, windowsFacts: { ...rep.windowsFacts, antivirus: ["Norton"] } });
    check("slow start + hard disk + full disk + other antivirus -> findings", ["slow to open", "hard disk", "almost full", "third-party antivirus"].every((t) => lvl(slow).join("|").includes(t)), lvl(slow).join("|"));
    const busy = mkr({ hardware: { ...rep.hardware, cpuThreads: 4 }, recent: Array.from({ length: 6 }, () => ({ at: "x", freeMB: 4000, lagMs: 0, tabs: 2, discarded: 0, procs: { Tab: { n: 2, cpu: 55, privMB: 300 }, GPU: { n: 1, cpu: 5, privMB: 100 } } })) });
    check("CPU is read as % of ALL threads (60% of 4 threads = 2.4 cores busy -> HIGH)", lvl(busy).some((s) => /HIGH:PBCalc keeps the processor busy/.test(s)), lvl(busy).join("|"));
    const calm = mkr({ hardware: { ...rep.hardware, ramFreeMB: 16000, onBattery: false, gpu: [{ name: "Some GPU", active: true, driver: "1" }] }, events: [], previousSession: null, exceptions: [], windowsFacts: { antivirus: ["Windows Defender"], disks: ["SSD/NVMe"], powerPlan: "Balanced", pbcalcEvents: [] }, storage: { ...rep.storage, disks: ["SSD/NVMe"], dataFolderFreeGB: 80 }, startupMs: { windowVisible: 900 }, recent: [1, 2, 3].map(() => ({ at: "x", freeMB: 16000, lagMs: 0, tabs: 1, discarded: 0, procs: { Tab: { n: 2, cpu: 0.1, privMB: 200 } } })), gpuFeatures: { gpu_compositing: "enabled", rasterization: "enabled" } });
    check("a healthy computer -> 'Nothing stands out'", lvl(calm).join("|").includes("INFO:Nothing stands out"), lvl(calm).join("|"));
    const cacheOnly = mkr({ hardware: { ...rep.hardware, ramTotalMB: 32000, ramFreeMB: 2500 }, recent: [{ at: "x", freeMB: 2500, sysCpu: 5, lagMs: 0, tabs: 1, discarded: 0, procs: {}, pages: [] }], memory: { ...rep.memory, available: { availableMB: 9000, pagesInPerSec: 0, pageReadsPerSec: 0, commitPct: 60, cacheMB: 500 } } });
    check("low FREE RAM but plenty AVAILABLE and no swapping -> LOW 'not a shortage', never HIGH", lvl(cacheOnly).some((x) => /LOW:Free RAM is low but Windows has memory to spare/.test(x)) && !lvl(cacheOnly).some((x) => /HIGH:The computer is short of memory/.test(x)), lvl(cacheOnly).join("|"));
    const swapR = mkr({ hardware: { ...rep.hardware, ramTotalMB: 32000, ramFreeMB: 400 }, recent: [{ at: "x", freeMB: 400, sysCpu: 5, lagMs: 0, tabs: 1, discarded: 0, procs: {}, pages: [] }], memory: { ...rep.memory, available: { availableMB: 300, pagesInPerSec: 900, pageReadsPerSec: 400, commitPct: 95, cacheMB: 50 } } });
    check("low available + hard page faults -> HIGH 'short of memory' and 'Windows is swapping'", lvl(swapR).some((x) => /HIGH:The computer is short of memory/.test(x)) && analyse(swapR).findings.find((f) => /short of memory/.test(f.title)).detail.includes("swapping"), lvl(swapR).join("|"));
    const slowStart = mkr({ startupMs: { appReady: 177, windowCreated: 250, shellStartLoading: 400, shellDomReady: 45000, shellFinishLoad: 45300, windowReadyToShow: 45898, windowVisible: 46425 }, otherPrograms: { openApps: [], topCpu: [{ name: "CompatTelRunner", cpuOfOneCore: 97 }] } });
    check("a 46 s start names the step ('shellStartLoading' -> 'shellDomReady') and what was busy (CompatTelRunner)", analyse(slowStart).findings.some((f) => /slow to open/.test(f.title) && /shellStartLoading' and 'shellDomReady/.test(f.detail) && /CompatTelRunner/.test(f.detail)), lvl(slowStart).join("|"));
    const prevR = mkr({ previousSession: { endedUncleanly: true, quitWasRequested: false, startedAt: "a", lastSeen: "b", ranSec: 2400, tabs: 6, recent: [{ freeMB: 310, sysCpu: 96, lagMs: 4200, pages: [{ p: 3, mb: 1500 }] }], exceptions: [{ message: "boom" }] } });
    check("a killed previous session -> HIGH 'ended abnormally' with what it looked like (memory gone, frozen, page size)", lvl(prevR).some((s) => /HIGH:PBCalc ended abnormally last time/.test(s)) && analyse(prevR).findings.find((f) => /ended abnormally/.test(f.title)).detail.includes("Memory had almost run out") && analyse(prevR).findings.find((f) => /ended abnormally/.test(f.title)).detail.includes("1500 MB"));
    const elsewhere = mkr({ recent: [1, 2, 3, 4].map(() => ({ at: "x", freeMB: 9000, sysCpu: 90, lagMs: 0, tabs: 1, discarded: 0, procs: { Tab: { n: 2, cpu: 0.2, privMB: 200 } }, pages: [] })), otherPrograms: { topCpu: [{ name: "SomeScanner", cpuOfOneCore: 400 }] } });
    check("the whole PC busy but PBCalc not -> 'Something ELSE is using the processor' and it names it", lvl(elsewhere).some((s) => /HIGH:Something ELSE is using the processor/.test(s)) && analyse(elsewhere).findings.find((f) => /ELSE/.test(f.title)).detail.includes("SomeScanner"));
    const commit = mkr({ memory: { windows: { physTotalMB: 8000, physFreeMB: 500, commitLimitMB: 10000, commitFreeMB: 600 }, pageFile: [{ sizeMB: 2000, usedMB: 1800, peakMB: 1900 }] } });
    check("commit nearly full + page file nearly full -> HIGH + MEDIUM", lvl(commit).some((s) => /HIGH:Windows is nearly out of memory/.test(s)) && lvl(commit).some((s) => /MEDIUM:The page file is almost full/.test(s)), lvl(commit).join("|"));
    const disk = mkr({ load: { cpuPct: 20, diskPct: 97, diskQueue: 4 } });
    check("disk busy 97 % with a queue -> HIGH 'the disk is the bottleneck'", lvl(disk).some((s) => /HIGH:The disk is the bottleneck/.test(s)));
    const nets = mkr({ network: { itComputerMs: 250, internetMs: 900, dnsMs: 1500 } });
    check("slow internet + slow name lookup + slow office network -> findings", ["internet connection is slow", "Name lookup is slow", "office network is slow"].every((t) => lvl(nets).join("|").includes(t)), lvl(nets).join("|"));
    const slowSite = mkr({ pageLoads: [1200, 9000, 14000, 16000, 20000].map((ms) => ({ at: "x", ms })), network: { itComputerMs: 5, internetMs: 30, dnsMs: 20 }, load: { cpuPct: 10, diskPct: 5, diskQueue: 0 } });
    check("slow page loads with a healthy PC and network -> 'the SITE itself is probably slow'", analyse(slowSite).findings.some((f) => /Pages take a long time/.test(f.title) && /SITE itself/.test(f.detail)));
    const modules = mkr({ windowsFacts: { ...rep.windowsFacts, pbcalcEvents: [{ at: "t1", id: 1000, app: "PBCalc.exe", module: "nvwgf2umx.dll", code: "0xc0000005" }, { at: "t2", id: 1002, app: "PBCalc.exe", module: "", code: "" }, { at: "t3", id: 1000, app: "PBCalc.exe", module: "PBCalc.exe", code: "0xc000012d" }] } });
    const mf = analyse(modules).findings.map((f) => f.title + " :: " + f.detail).join("\n");
    check("a crash in a graphics-driver module is called a graphics driver; 0xc000012d = out of virtual memory; a hang entry still says something", /nvwgf2umx\.dll \(a graphics driver/.test(mf) && /ran out of virtual memory/.test(mf) && /stopped responding to Windows/.test(mf), mf);
    const growing = mkr({ recent: Array.from({ length: 14 }, (_, i) => ({ at: "x", freeMB: 6000, sysCpu: 10, lagMs: 0, tabs: 3, discarded: 0, procs: {}, pages: [{ p: 2, mb: 300 + i * 60, cpu: 1 }] })) });
    check("a tab whose page grows from 300 to ~1100 MB -> 'Tab 2 keeps growing' (a leak), named by position", lvl(growing).some((s) => /MEDIUM:Tab 2 keeps growing/.test(s)), lvl(growing).join("|"));
    const rdp = mkr({ windows: { ...rep.windows, sessionType: "RDP-Tcp#3" } });
    check("a remote-desktop session -> HIGH", lvl(rdp).some((s) => /HIGH:PBCalc runs inside a remote session/.test(s)));
    const unavailable = mkr({ windowsFacts: { ...rep.windowsFacts, unavailable: true } });
    check("Windows' facts missing -> a LOW note, not a silent gap", lvl(unavailable).some((s) => /LOW:Windows' own facts are missing/.test(s)));
    check("no uncaught error in the main process", errors.length === 0, errors.join("|"));
  } catch (e) { check("no exception: " + (e && e.stack || e), false); }
  const failed = results.filter((r) => !r.pass).length;
  console.log("PBCALC_REPORT total=" + results.length + " failed=" + failed);
  app.exit(failed ? 1 : 0);
})();
